import type {Metadata} from "next";
import {Manrope} from "next/font/google";
import "./globals.css";
// import '@/shared/styles/main.scss'
import {ThemeProvider} from "@/providers/theme-provider";
import {ReactNode} from "react";
import {Header} from "@/widgets/Header/Header";
import {Cta} from "@/widgets/CTA/Cta";
import {Footer} from "@/widgets/Footer/Footer";
import {ReactQueryProvider} from "@/providers/react-query-provider";

const manrope = Manrope({
    variable: "--font-manrope",
    subsets: ["latin"],
    display: "swap",
    weight: ["400", "500", "600", "700"]
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
        <body
            className={`${manrope.variable} antialiased`}
        >
        <ReactQueryProvider>
            <ThemeProvider
                attribute="class"
                defaultTheme="system"
                enableSystem
                disableTransitionOnChange
            >
                <Header/>
                <div className='flex flex-col gap-20 lg:gap-30 2xl:gap-37.5'>
                    {children}
                    <Cta/>
                    <Footer/>
                </div>
            </ThemeProvider>
        </ReactQueryProvider>
        </body>
        </html>
    );
}
