import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";
// import '@/shared/styles/main.scss'
import {ThemeProvider} from "@/providers/theme-provider";
import {ReactNode} from "react";
import {Header} from "@/widgets/Header/Header";

const manrope = Manrope({
    variable: "--font-manrope",
    subsets: ["latin"],
    display: "swap",
    weight: ["400", "500", "600", "700"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
      <html lang="en" suppressHydrationWarning>
      <body
        className={`${manrope.variable} antialiased`}
      >
      <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
      >
          <Header/>
          {children}
      </ThemeProvider>
      </body>
    </html>
  );
}
